# Generated by Django 4.2.7 on 2025-09-26 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_colors', models.JSONField(default=list)),
                ('secondary_colors', models.JSONField(default=list)),
                ('fonts', models.JSONField(default=dict)),
                ('spacing', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_colors', models.JSONField(default=list)),
                ('wcag_compliant_colors', models.JSONField(default=list)),
                ('contrast_ratios', models.JSONField(default=dict)),
                ('accessibility_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_analyses', to='styleguide.styleguide')),
            ],
        ),
    ]
